name: GitHub Pages

on:
  push:
    branches:
      - main # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.146.5
          # hugo extend or not
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # 需要生成一个具有 repo 权限的 Personal Access Token
          # 并将其设置为仓库的 PERSONAL_TOKEN secret
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: SeaCatComplexes/SeaCatComplexes.github.io # Set the target repository
          publish_dir: ./public
          publish_branch: main # Set the target branch